gitSourceBranch = "main"
classOrder = ["Stellar", "Network", "SoundFX", "Scheduler"]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.png"
tagline = "Lightweight and easy to implement framework for Roblox games."

[home]
enabled = true
includeReadme = false

[footer]
style = "dark"
copyright = "Copyright © 2024 Bulk Games"
