title = "Stellar"
gitRepoUrl = "https://github.com/stellar-lua/stellar"

gitSourceBranch = "master"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
# favicon = ""

organizationName = "Stellar"
projectName = "Stellar"
baseUrl = "/"
tagline = "Elevate your games with the simplicity of Stellar."

[footer]
style = "dark"
copyright = "Copyright 2023, Bulk Games"
