gitSourceBranch = "main"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.png"
url = "https://stellar-lua.github.io"
baseUrl = "/"

[footer]
style = "dark"
copyright = "Copyright © 2024 Bulk Games"
